# Dev (just for fast compilation)
# Build Stage
FROM rust AS builder

WORKDIR /usr/src/app

ENV CARGO_HOME=/usr/local/cargo
ENV CARGO_TARGET_DIR=/usr/src/app/target

COPY Cargo.lock .
COPY Cargo.toml .
COPY . .

# Install necessary system dependencies
RUN apt update &&\
    rm -rf ~/.cache &&\
    apt clean all &&\
    apt install -y cmake &&\
    apt install -y clang &&\
    apt install -y pkgconf &&\
    apt-get install -y pkg-config openssl libssl-dev libpq-dev wget unzip

# Download the file using wget
RUN wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.2.0%2Bcpu.zip -O libtorch.zip
# Extract the contents of the ZIP file to /usr/libtorch
RUN unzip -o libtorch.zip -d /usr/lib
# Clean up unnecessary files
RUN rm libtorch.zip

# Set the environment variables
ENV LIBTORCH=/usr/lib/libtorch
ENV LD_LIBRARY_PATH=${LIBTORCH}/lib:$LD_LIBRARY_PATH
ENV RUSTBERT_CACHE=/usr/src/app/.cache/.rustbert/

# RUN rm -rf /root/.cache/.rustbert/

# Build the Rust application
RUN cargo build

# Expose the port
EXPOSE 8080
ENTRYPOINT ["/usr/src/app/target/debug/app"]
