app = "nabana-labs-api"
primary_region = "bog"

[experimental]
  cmd = ["/bin/app"]

[build]
  dockerfile = "Dockerfile"

[env]
  HOST = "0.0.0.0"
  PORT = "8080"
  API_URL="nabana-labs-api.fly.dev"
  API_TOKENS_EXPIRATION_TIME = "86400"
  MONGO_DB_NAME = "test"
  PRO_PRODUCT_ID="160756"
  PRO_MONTHLY_VARIANT_ID="202405"
  PRO_ANNUALLY_VARIANT_ID="202400"
  ENABLE_EMAIL_INTEGRATION="true"
  EMAIL_VERIFICATION_TEMPLATE_ID="1"
  BREVO_CUSTOMERS_LIST_ID="7"
  BREVO_MASTER_EMAIL_ADDRESS="no-reply@example.com"
  BREVO_MASTER_NAME="Nabana Labs [DEV MODE]"
  GOOGLE_OAUTH_CLIENT_ID="36457200694-c4rudq1jf1ne13mhr99oidskaf3rcsli.apps.googleusercontent.com"
  GOOGLE_OAUTH_CLIENT_REDIRECT_ENDPOINT="/api/identity/session/google"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
